CREATE DATABASE IF NOT EXISTS gdgoc_sch
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE gdgoc_sch;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
