spring.application.name=studymate
# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/studymatedb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console Configuration
spring.h2.console.enabled=true

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Firebase Configuration
firebase.config-path=file:config/firebase/serviceAccount.json